task: detect
mode: train
model: yolo26.pt
data: /root/MYDEIM/configs/deimv2/pest_yolov8.yaml

epochs: 200
patience: 200
batch: 16
imgsz: 640

optimizer: MuSGD
lr0: 0.00038
lrf: 0.882
momentum: 0.948
weight_decay: 0.00027

warmup_epochs: 0.99
warmup_momentum: 0.8
warmup_bias_lr: 0.00008

hsv_h: 0.013
hsv_s: 0.353
hsv_v: 0.194
degrees: 0.0
translate: 0.275
scale: 0.95
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.304
mosaic: 0.992
mixup: 0.427
copy_paste: 0.404

box: 9.83
cls: 0.65
dfl: 0.0

save: True
save_period: 10
cache: True
device: 0
workers: 8
project: ./outputs/yolo26_pest
name: exp

exist_ok: False
pretrained: True
verbose: True
seed: 0
deterministic: True
single_cls: False
rect: False
cos_lr: False
close_mosaic: 10
resume: False
amp: True
plots: True
val: True
end2end: True
